### PR TITLE
Add mu-plugin that disables Jetpack Protect on the fly to enable auto-login

### PR DESCRIPTION
**Pull request by wojtekn**
## Related issues

- Fixes https://github.com/Automattic/dotcom-forge/issues/9751

## Proposed Changes

I propose adding an mu-plugin that deactivates Jetpack Protect on the fly to avoid showing math questions in the login form. 

Before the change, it prevented users from using "WP Admin" auto-login on local sites that have Jetpack installed. When users used "WP Admin", it showed the login form with the math question:

Screenshot 2024-11-13 at 13 45 10

The expected behavior is to get the user automatically logged in to WP Admin, regardless of whether Jetpack is installed.

## Testing Instructions

1. Export a site that includes the Jetpack plugin, for example:
- from Activity Log for WoA site
- from Local dev env after installing the Jetpack plugin there
2. Import the site to Studio
3. Open the "WP Admin" link in Studio
4. Confirm that you were logged to WP Admin automatically

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

**Comment by nightnei** [comment]
@wojtekn I am not familiar with this process yet, could you please add more details for:
1) Export site that includes Jetpack plugin
2) Open WP Admin link and confirm that auto-login works - what does it mean `Open WP Admin link`?

**Comment by wojtekn** [comment]
@nightnei I've updated steps with more details, as well as the issue description.

**Review by katinthehatsite — APPROVED** [review]
The changes worked as expected for me 👍 

I compared the login with the trunk and was able to auto-login on this branch while on trunk, I got an extra login screen.

**Review by nightnei — APPROVED** [review]
Works as expected - in trunk I got login screen, but in this branch I was automatically authorized 👍

**Comment by wojtekn** [comment]
Thanks for review @katinthehatsite and @nightnei .

**Pull request merged**
