### PR TITLE
Studio: Images arent loaded in assistant responses

### PR DESCRIPTION
**Pull request by kozer**
Fixes https://github.com/Automattic/dotcom-forge/issues/7721

## Proposed Changes

This PR fixes a bug, where when the AI Assistant returns some images, those are not displayed.

## Testing Instructions

1. Open Studio
2. Create a site
3. Navigate to the assistant tab
4. Ask a question that probably will return an image.  Mine was "How can I add a new user"
5. Ensure that the images are displayed as expected

2024-06-21T11:11:42,039596244+03:00
2024-06-21T11:11:52,566657908+03:00

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

**Review by katinthehatsite — COMMENTED** [review]
The changes look good for me:

Screenshot 2024-06-21 at 11 08 06 AM

Should we also allow images from WooCommerce documentaion? 

Screenshot 2024-06-21 at 11 13 19 AM

**Comment by sejas** [comment]
@Automattic/yolo  What do you think about supporting all the images wildcard `*` instead of `*.wordpress.com`?
Supporting *.wordpress.com is almost the same, anyone can create a simple site and ask the Assistant to display that image inside the app.

**Comment by sejas** [comment]
Another option is removing the image. Something like:

```
<Markdown
	components={ { a: Anchor, code: CodeBlock, img: () => null } }
	remarkPlugins={ [ remarkGfm ] }
>
	{ children }
</Markdown>
```

**Comment by kozer** [comment]
> components={ { a: Anchor, code: CodeBlock, img: () => null } }

Let's do that instead! Thanks Antonio for the suggestion!

**Comment by kozer** [comment]
> Another option is removing the image. Something like:
> 
> ```
> <Markdown
> 	components={ { a: Anchor, code: CodeBlock, img: () => null } }
> 	remarkPlugins={ [ remarkGfm ] }
> >
> 	{ children }
> </Markdown>
> ```

I updated it to not show images.
cc: @katinthehatsite @sejas 
image

**Comment by wojtekn** [comment]
@sejas @kozer Should we modify the system prompt to let LLM know we are removing images so it won't include those?

**Comment by kozer** [comment]
> @sejas @kozer Should we modify the system prompt to let LLM know we are removing images so it won't include those?

I thought about that as well. However, I know that trying to limit the model using a system prompt, usually don't work as intended. 
@sejas , is currently working on updating the system prompt, so he can check this out.

One solution that may work better, is to handle what we store in the vector store. If we can remove the images before storing, it will solve better our problem.
What about creating a new ticket to explore that?
cc: @wojtekn

**Review by katinthehatsite — APPROVED** [review]
The change looks clear for me and I can't see the images anymore on my end:

Screenshot 2024-06-24 at 9 18 55 AM

Let's update the PR description to reflect that the decision that was reached on this PR is to not display the images at all. 

> One solution that may work better, is to handle what we store in the vector store. If we can remove the images before storing, it will solve better our problem.
What about creating a new ticket to explore that?

I would be okay with merging the current ticket as is to fix the broken images for now and then open a new ticket to see if there is a better approach to achieve hiding the images. Hence, I am approving this PR 👍

**Comment by sejas** [comment]
Thanks for removing the images.

> One solution that may work better, is to handle what we store in the vector store. If we can remove the images before storing, it will solve better our problem.
What about creating a new ticket to explore that?

@kozer , there you go https://github.com/Automattic/dotcom-forge/issues/7930

**Comment by sejas** [comment]
I closed https://github.com/Automattic/dotcom-forge/issues/7930 because we are avoiding to display images at system prompt level.

**Pull request merged**
