### PR TITLE
feat: Open assistant-generated links in a browser

### PR DESCRIPTION
**Pull request by dcalhoun**
Fixes https://github.com/Automattic/dotcom-forge/issues/7772.

## Proposed Changes

Enable users to navigate with links included in assistant responses,
opening the URL in the user's default browser.

## Testing Instructions

1. Navigate to the Assistant tab.
1. Request documentation on a subject; e.g., "How do I install a plugin?"
1. Verify clicking links within the assistant response open the link destination
   in the default browser.

## Pre-merge Checklist

- [x] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

**Comment by dcalhoun** [comment]
The proposed changes do not include automated tests as we currently [mock](https://github.com/Automattic/studio/blob/63ce507ccbf5eeaaa9ed1cc2c65307cc1c9655f9/src/__mocks__/react-markdown.ts) `react-markdown` due to the fact that it is an [ESM-only library](https://github.com/remarkjs/react-markdown/blob/7f32314d5bdab70f8551661ca36ef0deef29d02a/readme.md#install), for which Jest's [support](https://github.com/jestjs/jest/issues/9430) is experimental and unstable. Until we [configure](https://jestjs.io/docs/ecmascript-modules) Jest for ESM and remove the mock, testing the proposed changes is only possible in the form of asserting props passed to `react-markdown` and/or unit testing `Message` and `Anchor` independently, which does not seem all that valuable.

**Comment by dcalhoun** [comment]
My understanding is the failing Windows E2E tests are unrelated to these changes and currently under investigation (p1718622040527389-slack-C06DRMD6VPZ).

**Comment by fluiddot** [comment]
> My understanding is the failing Windows E2E tests are unrelated to these changes and currently under investigation (p1718622040527389-slack-C06DRMD6VPZ).

Yes, in fact, [we've disabled temporarily E2E tests on Windows until it's solved](https://github.com/Automattic/studio/pull/258). Sorry for the inconvenience 🙇 .

**Review by sejas — APPROVED** [review]
Nice work! I tested it and I confirm the links open the default browser.

I was thinking if we should check that `href` starts with `http` to avoid opening other protocols like `mailto`. But I guess there is no harm in opening other protocols too.

https://github.com/Automattic/studio/assets/779993/a89e7c4d-4ab5-4c2d-af3c-354b4b563a7b

**Pull request merged**
