### PR TITLE
Fix: Ensure plugin, theme, and WordPress updates succeed

### PR DESCRIPTION
**Pull request by SiobhyB**
Fixes: 6891-gh-Automattic/dotcom-forge, https://github.com/Automattic/studio/issues/100

Relates to: https://github.com/WordPress/playground-tools/issues/178

## Proposed Changes

A fix to prevent plugins, themes, and WordPress updates from failing was recently merged into the Emscripten repository in https://github.com/emscripten-core/emscripten/pull/21964. The next Emscripten release is due in around two weeks time, at which point a new release for PHP-WASM will be needed. As it may take some time for these updates to happen, and due to the high priority of this bug, I propose a temporary patch so that the fix gets to Studio users a bit quicker.

In this PR, I've updated the existing PHP-WASM patch to include the fix for update errors.

### Update an outdated plugin

* Install an outdated version of a plugin via _/wp-admin's_ Plugins section. One way to do this is to navigate to the Advanced View on a plugin's WordPress.org page and scroll to the bottom for a dropdown of older downloads. Example: [Gutenberg's Advanced View page](https://wordpress.org/plugins/gutenberg/advanced/).
* Refresh the Plugins section and choose the option to update alongside your newly installed plugin.
* Verify it updates as expected without error. You should notice the version number alongside the plugin change to the latest.

**Recording:**

https://github.com/WordPress/wordpress-playground/assets/2998162/4bf0125f-7ca8-4684-9f0b-48025f7bcef4

### Update an outdated version of WordPress

* Roll your local WordPress environment back to [an older version](https://en-gb.wordpress.org/download/releases/). 
* Click any of the prompts to update to the latest version of WordPress. These will generally be found in the header or footer section of any admin page, or by navigating directly to _Dashboard_ → _Updates_ in _/wp-admin_.
* Verify that the update is successful and that your site is now using the latest available version of WordPress.

**Recording:**

https://github.com/WordPress/wordpress-playground/assets/2998162/d21f6f72-00e8-4d2c-9cb8-e45633743619

### General smoke testing

Ensure no regressions by testing general functionality related to installations. It should still be possible to install plugins and themes as before.

## Pre-merge Checklist

- [x] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

**Review by sejas — APPROVED** [review]
@SiobhyB , First of all ... You are AWESOME!
Congrats for working on this bug until the very end and creating a PR on https://github.com/emscripten-core/emscripten 👏 

I think it's good idea to ship this change until the fix is released in the dependency libraries.

I tested updating a plugin and whole WordPress and both worked as expected. Yay!

### Update plugin
https://github.com/Automattic/studio/assets/779993/bfe8e9a2-6075-450f-a2d5-28394c70dadc

### Update WordPress


https://github.com/Automattic/studio/assets/779993/6e8141ba-a08d-41c4-a422-dcf7e910886a

**Comment by SiobhyB** [comment]
@sejas, thanks so much for all your help and support with this one, too! 🙌

**Comment by SiobhyB** [comment]
@wojtekn, is there still time to get this one into the `1.0.3` release?

**Comment by wojtekn** [comment]
@SiobhyB yes! 

Thanks for the fix, works great now. I tested it with my local site that uses MySQL and it updated Jetpack from 13.4.2 to 13.4.3 successfully. I also tested upgrading the whole WordPress core from 6.5.2 to 6.5.3 and from 6.4.3 to 6.5.3 and both cases worked fine, too.

**Pull request merged**
