### PR TITLE
fix(sync): align arrows of site url and add tooltip

### PR DESCRIPTION
**Pull request by nightnei**
Related to https://github.com/Automattic/dotcom-forge/issues/9510

## Proposed Changes
We should keep arrows always at the end of the URL, even if it's very long
Screenshot 2024-10-30 at 13 00 37

## Testing Instructions
1. Run STUDIO_SITE_SYNC=true npm start
2. Select any site -> Click on Sync tab -> click on Connect site button -> Select a site -> Click on "Connect' button
3. You should see the next<br />Screenshot 2024-10-30 at 13 03 12
4. Duplicate the URL a few times to make it long
5. Assert that that the arrow is located at the end of the URl and the URL is rendered as a few lines
<table>
<tr>
<td>BEFORE
<td>AFTER
</tr>
<tr>
<td>Screenshot 2024-10-30 at 13 05 33
<td>Screenshot 2024-10-30 at 13 04 59
</tr>
</table>

### CODE REVIEW

**Review by katinthehatsite — COMMENTED** [review]
It seems that there was some code merged today that truncates the long names:

https://github.com/Automattic/studio/blob/ba1d1df07d6897355fbea7a0c322cc9123a1bfcd/src/components/sync-connected-sites.tsx#L128

This solution works for me and also truncating works and I personally do not have strong preference. Perhaps @matt-west would be able to provide some suggestions

**Comment by nightnei** [comment]
@katinthehatsite but `truncate` add ellipsis, and it's not very nice to do for URL
Screenshot 2024-10-30 at 15 45 17

**Review by sejas — COMMENTED** [review]
For context, I introduced truncate in connected sites as part of the PR where I fixed the long domains inside the modal  https://github.com/Automattic/studio/pull/634.

Both multiline and ellipsis are good options for me, so I’ll defer to @matt-west  for further guidance. We should also check if it's ok having multiline in the connected sites and truncate in the modal.

**Comment by katinthehatsite** [comment]
I agree with @sejas - both solutions work so for me, it is a design decision.

**Comment by nightnei** [comment]
@katinthehatsite @sejas @matt-west I agree that both options are good, but the big benefit of multiline is giving the opportunity to show the whole URL for users which can improve UX. Good example was highlighted here (p1730314042394559-slack-C06DRMD6VPZ) with left sidebar. IMO, it's literally the same case

I am not sure that multiline is good thing for the left sidebar (but why not), but in the content part of Studio it IMO looks good. And multiline is better UX than forcing user to extend the app to see the whole URL 😅

**Comment by matt-west** [comment]
I think ellipsis makes sense here, but when you hover you should see the tooltip with the full URL. This is consistent with the behaviour in the global sites view.

Screenshot 2024-10-31 at 10 33 37

We should still display the external link arrow after the ellipsis for consistency.

**Comment by nightnei** [comment]
Added our tooltip:
Screenshot 2024-10-31 at 11 50 33

**Comment by wojtekn** [comment]
I noticed some issues:
- tooltip has fixed width so it gets a scrollbar
- long URL breaks Pull and Push buttons position

Screenshot 2024-10-31 at 14 25 34

**Comment by nightnei** [comment]
@wojtekn fixed:
Screenshot 2024-10-31 at 14 05 18

**Review by wojtekn — APPROVED** [review]
Looks good to me, thanks!

**Review by katinthehatsite — APPROVED** [review]
Looks good to me, thanks for the changes 👍 

Screenshot 2024-11-01 at 3 52 06 PM

**Comment by mokagio** [comment]
@nightnei 

image

Sorry to bother you, but to enable merging you'll need to merge or rebase on `trunk`. This is a consequence of #614. More info at pesfPa-1cY-p2 . Thanks!

**Pull request merged**
