### PR TITLE
Skip user data when exporting for push purposes

### PR DESCRIPTION
**Pull request by wojtekn**
## Related issues

- Fixes https://github.com/Automattic/dotcom-forge/issues/9994

## Proposed Changes

I propose to skip the `wp_users` and `wp_usermeta` tables from the archive prepared for Jetpack Backup restore. That way, VaultPress will preserve the original tables, so the Jetpack connection will be intact.

## Testing Instructions

1. Create a site with a Business plan
2. Create a staging site
3. Create a new site in Studio
4. Open Sync tab
5. Connect a site to a staging site
6. Push the site
7. Open the staging site at /wp-admin and confirm connection to WPcom is healthy - ensure that you see a Jetpack sidebar item.

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

**Review by ivan-ottinger — COMMENTED** [review]
The proposed changes look good, however, when following the testing steps, the synced staging site doesn't have the plugins active - since it was pushed from a fresh new Studio site. Am I missing something here?

We will also need to adjust the unit tests.

**Comment by wojtekn** [comment]
> The proposed changes look good, however, when following the testing steps, the synced staging site doesn't have the plugins active - since it was pushed from a fresh new Studio site. Am I missing something here?

We will automatically activate Jetpack via https://github.com/Automattic/studio/pull/724 as it is required to keep the connection between WPcom and WoA site.

> We will also need to adjust the unit tests.

Fixed in https://github.com/Automattic/studio/pull/727/commits/949f98d19415a3c2a14d8fd8d532c932daa59a34

**Comment by ivan-ottinger** [comment]
Thanks for sharing the details and fixing the tests, Wojtek.

> We will automatically activate Jetpack via https://github.com/Automattic/studio/pull/724 as it is required to keep the connection between WPcom and WoA site.

I am afraid this still doesn't work as expected in my tests.

I have rebased this PR locally on the latest `trunk` (that includes https://github.com/Automattic/studio/pull/724), pushed fresh Studio site to a fresh WPCOM staging site, but when trying to access WP Admin from Calypso, it still leads to:

```
https://staging-23f4-testatomic202412ivan.wpcomstaging.com/_wpcomsh_detect_support_session?redirect=%2Fwp-login.php%3Fredirect_to%3Dhttps%253A%252F%252Fstaging-23f4-testatomic202412ivan.wpcomstaging.com%252Fwp-admin%252F%26reauth%3D1%26disable-support-session-detection&nonce=a847e9934c
```

When trying to go to https://staging-23f4-testatomic202412ivan.wpcomstaging.com/wp-admin directly, the login doesn't work - since the user data are not present in the exported tables now:

Markup on 2024-12-10 at 10:36:13

**Comment by wojtekn** [comment]
> When trying to go to https://staging-23f4-testatomic202412ivan.wpcomstaging.com/wp-admin directly, the login doesn't work - since the user data are not present in the exported tables now:

It is expected that an 'admin' account doesn't exist there, as we preserve existing accounts, which are WordPress.com defaults. Are you able to log in using your WordPress.com credentials?

Note that this PR doesn't mean to fix the whole problem, but only the part which is caused by missing user accounts.

**Comment by ivan-ottinger** [comment]
> It is expected that an 'admin' account doesn't exist there, as we preserve existing accounts, which are WordPress.com defaults.

Yes, I understand this is expected since we are not exporting those tables in this PR. I just wanted to highlight that we cannot get in with the Stdio site credentials anymore - as opposed to the previous behavior when we could simply use those credentials (as the tables were exported from the Studio site).

> Are you able to log in using your WordPress.com credentials?

When checking the user list through CLI, I can still see my WordPress.com account on the WPCOM staging site. Also, Jetpack plugin is installed and active. However, I haven't found any easy way to log in*.

When trying to get to WP Admin through Calypso, we get to:

```
https://staging-23f4-testatomic202412ivan.wpcomstaging.com/_wpcomsh_detect_support_session?redirect=%2Fwp-login.php%3Fredirect_to%3Dhttps%253A%252F%252Fstaging-23f4-testatomic202412ivan.wpcomstaging.com%252Fwp-admin%252F%26reauth%3D1%26disable-support-session-detection&nonce=a847e9934c
```

> Note that this PR doesn't mean to fix the whole problem, but only the part which is caused by missing user accounts.

The reason I thought it would be possible to get to the WP Admin of the staging site was when reading the PR instructions:

> 7. Open the staging site at /wp-admin and confirm connection to WPcom is healthy - ensure that you see a Jetpack sidebar item.

---

*The easiest to get in that I can think of at the moment is to disconnect Jetpack and then reconnect it.

**Comment by wojtekn** [comment]
> When checking the user list through CLI, I can still see my WordPress.com account on the WPCOM staging site. Also, Jetpack plugin is installed and active. However, I haven't found any easy way to log in*.

I think it may mean that SSO is disabled after Jetpack is activated that way. Could you please try logging in to WP Admin using WordPress.com credentials and check if SSO is inactive? If yes, activating should help. However, I think it's more related to https://github.com/Automattic/studio/pull/724 than this PR.

**Comment by ivan-ottinger** [comment]
> I think it may mean that SSO is disabled after Jetpack is activated that way. Could you please try logging in to WP Admin using WordPress.com credentials and check if SSO is inactive? If yes, activating should help. However, I think it's more related to https://github.com/Automattic/studio/pull/724 than this PR.

Great idea. Yes, the SSO was disabled. As soon as it is enabled, one can get to WP Admin. 🙂 

✅ Approving this PR.

**Review by ivan-ottinger — APPROVED** [review]

**Comment by ivan-ottinger** [comment]
> If yes, activating should help. However, I think it's more related to https://github.com/Automattic/studio/pull/724 than this PR.

I looked into this further and initially thought it could be enough to run `wp jetpack module sso activate` when Jetpack is being activated in `activateJetpackIfNeeded` (introduced in https://github.com/Automattic/studio/pull/724). But after running a couple of tests, this doesn't seem to be the case.

So far it looks like we may need to enable the SSO module on the WPCOM side instead - once the import is finished.

Update: I have added comment to the related issue: https://github.com/Automattic/jetpack-backup-team/issues/739#issuecomment-2531676121.

**Comment by fredrikekelund** [comment]
@ivan-ottinger, if we want to stick to the approach we took in https://github.com/Automattic/studio/pull/724 (smooth out Jetpack connection kinks on the client rather than the back-end), then we should try and find out which `wp_options` setting controls whether the Jetpack SSO module is active.

**Comment by fredrikekelund** [comment]
@ivan-ottinger @wojtekn, looks like that'd be `jetpack_active_modules`. On my test site, it contains the following data:

```
array (
  0 => 'carousel',
  1 => 'comment-likes',
  2 => 'comments',
  3 => 'contact-form',
  4 => 'copy-post',
  5 => 'custom-content-types',
  6 => 'custom-css',
  7 => 'enhanced-distribution',
  8 => 'google-analytics',
  9 => 'gravatar-hovercards',
  10 => 'infinite-scroll',
  11 => 'json-api',
  12 => 'likes',
  13 => 'masterbar',
  14 => 'notes',
  15 => 'photon',
  16 => 'photon-cdn',
  17 => 'protect',
  18 => 'publicize',
  19 => 'search',
  20 => 'seo-tools',
  21 => 'sharedaddy',
  22 => 'shortcodes',
  23 => 'shortlinks',
  24 => 'sitemaps',
  25 => 'sso',
  26 => 'stats',
  27 => 'subscriptions',
  28 => 'tiled-gallery',
  29 => 'verification-tools',
  30 => 'videopress',
  31 => 'widget-visibility',
  32 => 'widgets',
  33 => 'related-posts',
  34 => 'google-fonts',
  35 => 'blaze',
  36 => 'post-by-email',
  37 => 'blocks',
)
```

**Comment by fredrikekelund** [comment]
Maybe we should find out what the default value for that option is and insert it the same way we do `active_plugins` in https://github.com/Automattic/studio/pull/724..?

**Comment by ivan-ottinger** [comment]
> Maybe we should find out what the default value for that option is and insert it the same way we do active_plugins in https://github.com/Automattic/studio/pull/724..?

That sounds good to me. 👌🏼 

I wasn't aware the Jetpack modules are stored in the site options.

The default value on a fresh Atomic site I just created looks like this:

```
{
  "jetpack_active_modules": [
    "blocks",
    "carousel",
    "comment-likes",
    "comments",
    "contact-form",
    "copy-post",
    "custom-content-types",
    "gravatar-hovercards",
    "infinite-scroll",
    "json-api",
    "latex",
    "likes",
    "notes",
    "photon",
    "photon-cdn",
    "post-by-email",
    "protect",
    "publicize",
    "search",
    "seo-tools",
    "sharedaddy",
    "shortcodes",
    "shortlinks",
    "sitemaps",
    "sso",
    "stats",
    "subscriptions",
    "tiled-gallery",
    "verification-tools",
    "videopress",
    "widget-visibility",
    "widgets",
    "related-posts",
    "google-fonts",
    "blaze"
  ]
}
```

As soon as the SSO module is disabled, the option array will be missing that one element.

**Comment by wojtekn** [comment]
Thanks for the additional research @ivan-ottinger and @fredrikekelund .

As it seems we may need to do more steps to activate Jetpack, I think it would be safer to do so server-side when the Jetpack module is available instead of trying to enable it in the database before preparing a local dump.

I opened a work-in-progress diff for that: D168266-code

**Pull request merged**
