### PR TITLE
Add translations for 1.0.4

### PR DESCRIPTION
**Pull request by wojtekn**
Related to pfHvTO-7o-p2

## Proposed Changes

I propose to add translations exported from GlotPress.

## Testing Instructions

1. Test if the app is available in the English locale
2. Test if the app is available for another locale
3. Test RTL language

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

**Review by katinthehatsite — APPROVED** [review]
Looking good, thanks for updating the translations!

**Comment by nguyenquanghoang** [comment]
I have contributed a Studio translation on GlotPress, how can I add it to the Studio? And how can I display that language in Studio?

**Comment by wojtekn** [comment]
Thanks for contributing to the Studio @nguyenquanghoang ! Could you please clarify which language you worked on? I'm happy to review it and bring the translations to the Studio codebase.

**Comment by nguyenquanghoang** [comment]
I am working on Vietnamese language translation https://translate.wordpress.com/projects/studio/vi/default/

**Comment by wojtekn** [comment]
@nguyenquanghoang, thanks for clarifying that. I see it's 20% complete, and it should be closer to 100% to include it in the package. To use the Vietnamese in the Studio locally, during development, you can:

1. Pull and set up the project locally
2. Add new language in the `src/lib/locale.ts`
3. Follow https://github.com/Automattic/studio/blob/trunk/docs/localization.md to export language from GlotPress and import to Studio

**Comment by nguyenquanghoang** [comment]
@wojtekn I don't know where to send the translation **approval request,** but currently I have translated 100% of the String, you can export it as the attached image.

**Comment by nguyenquanghoang** [comment]
@wojtekn I have exported, but currently I do not have Uploads permission

Uploads are disabled

**Comment by nguyenquanghoang** [comment]
The translation has now been 100% approved @wojtekn https://translate.wordpress.com/projects/studio/vi/default/

**Pull request merged**
