### PR TITLE
Update playground to version 0.9.44

### LINKED ISSUE #358: Connecting to Remote MySQL Database Causes Local Site Server to Crash
### Quick summary

When performing actions on sites connected to a remote MySQL database, WASM errors cause runtime errors and the site server crashes. WordPress Studio v1.0.5 on Windows.

Errors were very frequent when trying to create sites connected to a remote MySQL database and the Studio app has to be restarted in order to start the sites again. Any troubleshooting tips and workarounds are appreciated.

### Steps to reproduce

I'm working on identifying a concrete set of actions that will always trigger a WASM error, but they've been occur frequently when sending requests to sites connected to a remote MySQL database. Triggering any WASM error caused a runtime error.

1. Add a site
2. Configure the site to connect to a remote MySQL database ([Documentation](https://developer.wordpress.com/docs/developer-tools/studio/#use-studio-with-mysql-server))
a. Navigate to the wp-content directory and delete the db.php file and the database directory.
b. Navigate to the mu-plugins directory and delete sqlite-database-integration-main directory.
c. Update wp-config.php file and fill in your MySQL server’s credentials.
3. Click around the admin dashboard performing common actions like installing plugins and creating posts.

### What you expected to happen

I expected an error message to appear in the browser and for the site to continue running on localhost.

### What actually happened

The site server stops running, but Studio continues to display the site as "Running" and I'm then unable to stop the site. Clicking the stop button loads for a long time before display the "Something's Broken" error message and prompting the user to restart.

### Impact

Some (< 50%)

### Available workarounds?

No but the app is still usable

### Platform

Windows

### Logs or notes

I encountered a variety of WASM errors, including one mentioned in this ([WP Playground issue](https://github.com/WordPress/wordpress-playground/issues/1052)).

Edit: The error log below was output while running the application using the v1.0.5 source code on Node.js v20.9.0. I also tried installing and running the app using WSL (Ubuntu) and encountered the same errors.

```
ErrorEvent2 {
  type: 'error',
  defaultPrevented: false,
  cancelable: false,
  timeStamp: 40816.1060000062
}
RuntimeError: null function or function signature mismatch
    at mysqlnd_read_header (wasm://wasm/033c9c8e:wasm-function[3937]:0x28d533)
    at mysqlnd_read_packet_header_and_body (wasm://wasm/033c9c8e:wasm-function[1299]:0xb9d80)
    at php_mysqlnd_rset_field_read (wasm://wasm/033c9c8e:wasm-function[10709]:0x5b48cf)
    ... 3 lines matching cause stack trace ...
    at mysqlnd_mysqlnd_command_reap_result_pub (wasm://wasm/033c9c8e:wasm-function[11372]:0x5f7b33)
    at mysqlnd_mysqlnd_conn_data_reap_query_pub (wasm://wasm/033c9c8e:wasm-function[11324]:0x5f4af9)
    at mysqlnd_mysqlnd_conn_data_query_pub (wasm://wasm/033c9c8e:wasm-function[11325]:0x5f4c1f)
    at zif_mysqli_query (wasm://wasm/033c9c8e:wasm-function[8271]:0x4e9fbb)
    at ZEND_DO_ICALL_SPEC_RETVAL_USED_HANDLER (wasm://wasm/033c9c8e:wasm-function[13813]:0x6a9e50)
    at execute_ex (wasm://wasm/033c9c8e:wasm-function[12270]:0x640683)
    at zend_call_function (wasm://wasm/033c9c8e:wasm-function[408]:0x2aa9a)
    at php_replace_in_subject_func (wasm://wasm/033c9c8e:wasm-function[5456]:0x3986f0)
    at preg_replace_func_impl (wasm://wasm/033c9c8e:wasm-function[5342]:0x37ef8b)
    at zif_preg_replace_callback (wasm://wasm/033c9c8e:wasm-function[8103]:0x4cd299) {
  cause: Error
      at Asyncify.handleSleep (...\node_modules\@php-wasm\node\index.cjs:26420:45)
      at _wasm_poll_socket (...\node_modules\@php-wasm\node\index.cjs:25297:21)
      at php_pollfd_for (wasm://wasm/033c9c8e:wasm-function[978]:0x9134f)
      at php_sockop_read (wasm://wasm/033c9c8e:wasm-function[10629]:0x5acff4)
      at php_openssl_sockop_io (wasm://wasm/033c9c8e:wasm-function[5475]:0x3a0ac3)
      at php_openssl_sockop_read (wasm://wasm/033c9c8e:wasm-function[10681]:0x5b3662)
      at _php_stream_fill_read_buffer (wasm://wasm/033c9c8e:wasm-function[3222]:0x20d9b3)
      at _php_stream_read (wasm://wasm/033c9c8e:wasm-function[221]:0x13618)
      at mysqlnd_mysqlnd_vio_network_read_pub (wasm://wasm/033c9c8e:wasm-function[11166]:0x5ea1a3)
      at mysqlnd_mysqlnd_pfc_receive_pub (wasm://wasm/033c9c8e:wasm-function[11272]:0x5f1745)
      at mysqlnd_read_packet_header_and_body (wasm://wasm/033c9c8e:wasm-function[1299]:0xb9e24)
      at php_mysqlnd_rset_field_read (wasm://wasm/033c9c8e:wasm-function[10709]:0x5b48cf)
      at mysqlnd_mysqlnd_res_meta_read_metadata_pub (wasm://wasm/033c9c8e:wasm-function[11230]:0x5ef28b)
      at mysqlnd_mysqlnd_res_read_result_metadata_pub (wasm://wasm/033c9c8e:wasm-function[11228]:0x5ef1bf)
      at mysqlnd_query_read_result_set_header (wasm://wasm/033c9c8e:wasm-function[11156]:0x5e92d7)
      at mysqlnd_mysqlnd_command_reap_result_pub (wasm://wasm/033c9c8e:wasm-function[11372]:0x5f7b33)
}
Error: null function or function signature mismatch
    at #handleRequest (...\node_modules\@php-wasm\node\index.cjs:73301:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _NodePHP.run (...\node_modules\@php-wasm\node\index.cjs:72995:24)
    at async #dispatchToPHP (...\node_modules\@php-wasm\node\index.cjs:72521:16)
    at async PHPRequestHandler.request (...\node_modules\@php-wasm\node\index.cjs:72433:14)
    at async PHPBrowser.request (...\node_modules\@php-wasm\node\index.cjs:72215:22) {
  cause: Error: Rethrown
      at UnhandledRejectionsTarget.errorListener (...\node_modules\@php-wasm\node\index.cjs:73267:28)
      at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
      at UnhandledRejectionsTarget.dispatchEvent (node:internal/event_target:742:26)
      at runtime.asm.<computed> (...\node_modules\@php-wasm\node\index.cjs:71764:20)
      at invoke_iiiii (...\node_modules\@php-wasm\node\index.cjs:26272:14)
      at php_execute_script (wasm://wasm/033c9c8e:wasm-function[10854]:0x5c16d4)
      at dynCall_ii (wasm://wasm/033c9c8e:wasm-function[12472]:0x64a6d8)
      at ret.<computed> (...\node_modules\@php-wasm\node\index.cjs:25432:33)
      at runtime.asm.<computed> (...\node_modules\@php-wasm\node\index.cjs:71751:18)
      at invoke_ii (...\node_modules\@php-wasm\node\index.cjs:26206:14)
      at wasm_sapi_handle_request (wasm://wasm/033c9c8e:wasm-function[9474]:0x556618)
      at ret.<computed> (...\node_modules\@php-wasm\node\index.cjs:25432:33)
      at runtime.asm.<computed> (...\node_modules\@php-wasm\node\index.cjs:71751:18)
      at Object.doRewind (...\node_modules\@php-wasm\node\index.cjs:25515:14)
      at ...\node_modules\@php-wasm\node\index.cjs:25538:45
      at ...\node_modules\@php-wasm\node\index.cjs:25364:11 {
    cause: RuntimeError: null function or function signature mismatch
        at mysqlnd_read_header (wasm://wasm/033c9c8e:wasm-function[3937]:0x28d533)
        at mysqlnd_read_packet_header_and_body (wasm://wasm/033c9c8e:wasm-function[1299]:0xb9d80)
        at php_mysqlnd_rset_field_read (wasm://wasm/033c9c8e:wasm-function[10709]:0x5b48cf)
        ... 3 lines matching cause stack trace ...
        at mysqlnd_mysqlnd_command_reap_result_pub (wasm://wasm/033c9c8e:wasm-function[11372]:0x5f7b33)
        at mysqlnd_mysqlnd_conn_data_reap_query_pub (wasm://wasm/033c9c8e:wasm-function[11324]:0x5f4af9)
        at mysqlnd_mysqlnd_conn_data_query_pub (wasm://wasm/033c9c8e:wasm-function[11325]:0x5f4c1f)
        at zif_mysqli_query (wasm://wasm/033c9c8e:wasm-function[8271]:0x4e9fbb)
        at ZEND_DO_ICALL_SPEC_RETVAL_USED_HANDLER (wasm://wasm/033c9c8e:wasm-function[13813]:0x6a9e50)
        at execute_ex (wasm://wasm/033c9c8e:wasm-function[12270]:0x640683)
        at zend_call_function (wasm://wasm/033c9c8e:wasm-function[408]:0x2aa9a)
        at php_replace_in_subject_func (wasm://wasm/033c9c8e:wasm-function[5456]:0x3986f0)
        at preg_replace_func_impl (wasm://wasm/033c9c8e:wasm-function[5342]:0x37ef8b)
        at zif_preg_replace_callback (wasm://wasm/033c9c8e:wasm-function[8103]:0x4cd299) {
      cause: Error
          at Asyncify.handleSleep (...\node_modules\@php-wasm\node\index.cjs:26420:45)
          at _wasm_poll_socket (...\node_modules\@php-wasm\node\index.cjs:25297:21)
          at php_pollfd_for (wasm://wasm/033c9c8e:wasm-function[978]:0x9134f)
          at php_sockop_read (wasm://wasm/033c9c8e:wasm-function[10629]:0x5acff4)
          at php_openssl_sockop_io (wasm://wasm/033c9c8e:wasm-function[5475]:0x3a0ac3)
          at php_openssl_sockop_read (wasm://wasm/033c9c8e:wasm-function[10681]:0x5b3662)
          at _php_stream_fill_read_buffer (wasm://wasm/033c9c8e:wasm-function[3222]:0x20d9b3)
          at _php_stream_read (wasm://wasm/033c9c8e:wasm-function[221]:0x13618)
          at mysqlnd_mysqlnd_vio_network_read_pub (wasm://wasm/033c9c8e:wasm-function[11166]:0x5ea1a3)
          at mysqlnd_mysqlnd_pfc_receive_pub (wasm://wasm/033c9c8e:wasm-function[11272]:0x5f1745)
          at mysqlnd_read_packet_header_and_body (wasm://wasm/033c9c8e:wasm-function[1299]:0xb9e24)
          at php_mysqlnd_rset_field_read (wasm://wasm/033c9c8e:wasm-function[10709]:0x5b48cf)
          at mysqlnd_mysqlnd_res_meta_read_metadata_pub (wasm://wasm/033c9c8e:wasm-function[11230]:0x5ef28b)
          at mysqlnd_mysqlnd_res_read_result_metadata_pub (wasm://wasm/033c9c8e:wasm-function[11228]:0x5ef1bf)
          at mysqlnd_query_read_result_set_header (wasm://wasm/033c9c8e:wasm-function[11156]:0x5e92d7)
          at mysqlnd_mysqlnd_command_reap_result_pub (wasm://wasm/033c9c8e:wasm-function[11372]:0x5f7b33)
    },
    betterMessage: 'null function or function signature mismatch'
  }
}
Trace: Error: null function or function signature mismatch
    at #handleRequest (...\node_modules\@php-wasm\node\index.cjs:73301:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _NodePHP.run (...\node_modules\@php-wasm\node\index.cjs:72995:24)
    at async #dispatchToPHP (...\node_modules\@php-wasm\node\index.cjs:72521:16)
    at async PHPRequestHandler.request (...\node_modules\@php-wasm\node\index.cjs:72433:14)
    at async PHPBrowser.request (...\node_modules\@php-wasm\node\index.cjs:72215:22) {
  cause: Error: Rethrown
      at UnhandledRejectionsTarget.errorListener (...\node_modules\@php-wasm\node\index.cjs:73267:28)
      at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
      at UnhandledRejectionsTarget.dispatchEvent (node:internal/event_target:742:26)
      at runtime.asm.<computed> (...\node_modules\@php-wasm\node\index.cjs:71764:20)
      at invoke_iiiii (...\node_modules\@php-wasm\node\index.cjs:26272:14)
      at php_execute_script (wasm://wasm/033c9c8e:wasm-function[10854]:0x5c16d4)
      at dynCall_ii (wasm://wasm/033c9c8e:wasm-function[12472]:0x64a6d8)
      at ret.<computed> (...\node_modules\@php-wasm\node\index.cjs:25432:33)
      at runtime.asm.<computed> (...\node_modules\@php-wasm\node\index.cjs:71751:18)
      at invoke_ii (...\node_modules\@php-wasm\node\index.cjs:26206:14)
      at wasm_sapi_handle_request (wasm://wasm/033c9c8e:wasm-function[9474]:0x556618)
      at ret.<computed> (...\node_modules\@php-wasm\node\index.cjs:25432:33)
      at runtime.asm.<computed> (...\node_modules\@php-wasm\node\index.cjs:71751:18)
      at Object.doRewind (...\node_modules\@php-wasm\node\index.cjs:25515:14)
      at ...\node_modules\@php-wasm\node\index.cjs:25538:45
      at ...\node_modules\@php-wasm\node\index.cjs:25364:11 {
    cause: RuntimeError: null function or function signature mismatch
        at mysqlnd_read_header (wasm://wasm/033c9c8e:wasm-function[3937]:0x28d533)
        at mysqlnd_read_packet_header_and_body (wasm://wasm/033c9c8e:wasm-function[1299]:0xb9d80)
        at php_mysqlnd_rset_field_read (wasm://wasm/033c9c8e:wasm-function[10709]:0x5b48cf)
        ... 3 lines matching cause stack trace ...
        at mysqlnd_mysqlnd_command_reap_result_pub (wasm://wasm/033c9c8e:wasm-function[11372]:0x5f7b33)
        at mysqlnd_mysqlnd_conn_data_reap_query_pub (wasm://wasm/033c9c8e:wasm-function[11324]:0x5f4af9)
        at mysqlnd_mysqlnd_conn_data_query_pub (wasm://wasm/033c9c8e:wasm-function[11325]:0x5f4c1f)
        at zif_mysqli_query (wasm://wasm/033c9c8e:wasm-function[8271]:0x4e9fbb)
        at ZEND_DO_ICALL_SPEC_RETVAL_USED_HANDLER (wasm://wasm/033c9c8e:wasm-function[13813]:0x6a9e50)
        at execute_ex (wasm://wasm/033c9c8e:wasm-function[12270]:0x640683)
        at zend_call_function (wasm://wasm/033c9c8e:wasm-function[408]:0x2aa9a)
        at php_replace_in_subject_func (wasm://wasm/033c9c8e:wasm-function[5456]:0x3986f0)
        at preg_replace_func_impl (wasm://wasm/033c9c8e:wasm-function[5342]:0x37ef8b)
        at zif_preg_replace_callback (wasm://wasm/033c9c8e:wasm-function[8103]:0x4cd299) {
      cause: Error
          at Asyncify.handleSleep (...\node_modules\@php-wasm\node\index.cjs:26420:45)
          at _wasm_poll_socket (...\node_modules\@php-wasm\node\index.cjs:25297:21)
          at php_pollfd_for (wasm://wasm/033c9c8e:wasm-function[978]:0x9134f)
          at php_sockop_read (wasm://wasm/033c9c8e:wasm-function[10629]:0x5acff4)
          at php_openssl_sockop_io (wasm://wasm/033c9c8e:wasm-function[5475]:0x3a0ac3)
          at php_openssl_sockop_read (wasm://wasm/033c9c8e:wasm-function[10681]:0x5b3662)
          at _php_stream_fill_read_buffer (wasm://wasm/033c9c8e:wasm-function[3222]:0x20d9b3)
          at _php_stream_read (wasm://wasm/033c9c8e:wasm-function[221]:0x13618)
          at mysqlnd_mysqlnd_vio_network_read_pub (wasm://wasm/033c9c8e:wasm-function[11166]:0x5ea1a3)
          at mysqlnd_mysqlnd_pfc_receive_pub (wasm://wasm/033c9c8e:wasm-function[11272]:0x5f1745)
          at mysqlnd_read_packet_header_and_body (wasm://wasm/033c9c8e:wasm-function[1299]:0xb9e24)
          at php_mysqlnd_rset_field_read (wasm://wasm/033c9c8e:wasm-function[10709]:0x5b48cf)
          at mysqlnd_mysqlnd_res_meta_read_metadata_pub (wasm://wasm/033c9c8e:wasm-function[11230]:0x5ef28b)
          at mysqlnd_mysqlnd_res_read_result_metadata_pub (wasm://wasm/033c9c8e:wasm-function[11228]:0x5ef1bf)
          at mysqlnd_query_read_result_set_header (wasm://wasm/033c9c8e:wasm-function[11156]:0x5e92d7)
          at mysqlnd_mysqlnd_command_reap_result_pub (wasm://wasm/033c9c8e:wasm-function[11372]:0x5f7b33)
    },
    betterMessage: 'null function or function signature mismatch'
  }
}
    at ...\.webpack\main\siteServerProcess.js:53952:99
    at Generator.throw (<anonymous>)
    at rejected (...\.webpack\main\siteServerProcess.js:53884:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


  WASM ERROR

  "unreachable" WASM instruction executed.

  The typical reason is a PHP function missing from the ASYNCIFY_ONLY
  list when building PHP.wasm.

  You will need to file a new issue in the WordPress Playground repository
  and paste this error message there:

  https://github.com/WordPress/wordpress-playground/issues/new

  If you're a core developer, the typical fix is to:

  * Isolate a minimal reproduction of the error
  * Add a reproduction of the error to php-asyncify.spec.ts in the WordPress Playground repository
  * Run 'npm run fix-asyncify'
  * Commit the changes, push to the repo, release updated NPM packages

  Below is a list of all the PHP functions found in the stack trace to
  help with the minimal reproduction. If they're all already listed in
  the Dockerfile, you'll need to trigger this error again with long stack
  traces enabled. In node.js, you can do it using the --stack-trace-limit=100
  CLI option:

      * php_pollfd_for
      * php_sockop_read
      * php_openssl_sockop_io
      * php_openssl_sockop_read
      * _php_stream_fill_read_buffer
      * _php_stream_read
      * mysqlnd_mysqlnd_vio_network_read_pub
      * mysqlnd_mysqlnd_pfc_receive_pub
      * mysqlnd_read_packet_header_and_body
      * php_mysqlnd_rset_field_read
      * mysqlnd_mysqlnd_res_meta_read_metadata_pub
      * mysqlnd_mysqlnd_res_read_result_metadata_pub
      * mysqlnd_query_read_result_set_header
      * mysqlnd_mysqlnd_command_reap_result_pub


wasm://wasm/033c9c8e:1


RuntimeError: unreachable
    at dynCall_iiiii (wasm://wasm/033c9c8e:wasm-function[12469]:0x64a48e)
    at ret.<computed> (...\node_modules\@php-wasm\node\index.cjs:25432:33)
    at runtime.asm.<computed> (...\node_modules\@php-wasm\node\index.cjs:71751:18)
    at invoke_iiiii (...\node_modules\@php-wasm\node\index.cjs:26272:14)
    at php_execute_script (wasm://wasm/033c9c8e:wasm-function[10854]:0x5c16d4)
    at dynCall_ii (wasm://wasm/033c9c8e:wasm-function[12472]:0x64a6d8)
    at ret.<computed> (...\node_modules\@php-wasm\node\index.cjs:25432:33)
    at runtime.asm.<computed> (...\node_modules\@php-wasm\node\index.cjs:71751:18)
    at invoke_ii (...\node_modules\@php-wasm\node\index.cjs:26206:14)
    at wasm_sapi_handle_request (wasm://wasm/033c9c8e:wasm-function[9474]:0x556618)
    at ret.<computed> (...\node_modules\@php-wasm\node\index.cjs:25432:33)
    at runtime.asm.<computed> (...\node_modules\@php-wasm\node\index.cjs:71751:18)
    at Object.doRewind (...\node_modules\@php-wasm\node\index.cjs:25515:14)
    at ...\node_modules\@php-wasm\node\index.cjs:25538:45
    at ...\node_modules\@php-wasm\node\index.cjs:25364:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error
      at Asyncify.handleSleep (...\node_modules\@php-wasm\node\index.cjs:26420:45)
      at _wasm_poll_socket (...\node_modules\@php-wasm\node\index.cjs:25297:21)
      at php_pollfd_for (wasm://wasm/033c9c8e:wasm-function[978]:0x9134f)
      at php_sockop_read (wasm://wasm/033c9c8e:wasm-function[10629]:0x5acff4)
      at php_openssl_sockop_io (wasm://wasm/033c9c8e:wasm-function[5475]:0x3a0ac3)
      at php_openssl_sockop_read (wasm://wasm/033c9c8e:wasm-function[10681]:0x5b3662)
      at _php_stream_fill_read_buffer (wasm://wasm/033c9c8e:wasm-function[3222]:0x20d9b3)
      at _php_stream_read (wasm://wasm/033c9c8e:wasm-function[221]:0x13618)
      at mysqlnd_mysqlnd_vio_network_read_pub (wasm://wasm/033c9c8e:wasm-function[11166]:0x5ea1a3)
      at mysqlnd_mysqlnd_pfc_receive_pub (wasm://wasm/033c9c8e:wasm-function[11272]:0x5f1745)
      at mysqlnd_read_packet_header_and_body (wasm://wasm/033c9c8e:wasm-function[1299]:0xb9e24)
      at php_mysqlnd_rset_field_read (wasm://wasm/033c9c8e:wasm-function[10709]:0x5b48cf)
      at mysqlnd_mysqlnd_res_meta_read_metadata_pub (wasm://wasm/033c9c8e:wasm-function[11230]:0x5ef28b)
      at mysqlnd_mysqlnd_res_read_result_metadata_pub (wasm://wasm/033c9c8e:wasm-function[11228]:0x5ef1bf)
      at mysqlnd_query_read_result_set_header (wasm://wasm/033c9c8e:wasm-function[11156]:0x5e92d7)
      at mysqlnd_mysqlnd_command_reap_result_pub (wasm://wasm/033c9c8e:wasm-function[11372]:0x5f7b33)
}

Node.js v20.9.0
Sentry Logger [error]: Transport disabled
Sentry Logger [error]: Transport disabled
Loaded user data from C:\Users\...\AppData\Roaming\Studio\appdata-v1.json
Saved user data to C:\Users\...\AppData\Roaming\Studio\appdata-v1.json
Stopping server with ID 81d03e79-be19-4fc4-9ddb-1d4c733dc1b4
```

"Stopping server with ID" was logged after trying to stop the site and was the last log event before the app displayed the "Something's broken" error.

### PR DESCRIPTION
**Pull request by jeroenpf**
## Proposed Changes

- Update Playground from 0.9.39 to version 0.9.44 
- This update contains various improvements including MySQL compatibility fixes

## Testing Instructions

-

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

**Comment by fluiddot** [comment]
For reference, here are the changes introduced in Playground:
https://github.com/WordPress/wordpress-playground/compare/v0.9.39...v0.9.44

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

I've tested a site using MySQL and I didn't find any crash as outlined in https://github.com/Automattic/studio/issues/358 🎊 !

**Review by wojtekn — APPROVED** [review]

**Comment by wojtekn** [comment]
Looks good. Thanks for fixing this in the upstream @jeroenpf  (https://github.com/WordPress/wordpress-playground/pull/1752) and upgrading Playground in Studio!

**Comment by wojtekn** [comment]
I've tested it more, but it seems that when I try to start the site configured to use MySQL, it crashes:

```
node:internal/errors:497
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "set-cookie"
    at ServerResponse.setHeader (node:_http_outgoing:655:3)
    at /Volumes/Sites/local-environment/.webpack/main/siteServerProcess.js:61899:21
    at Generator.next (<anonymous>)
    at fulfilled (/Volumes/Sites/local-environment/.webpack/main/siteServerProcess.js:61839:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}

Node.js v20.9.0
```

When I use Studio 1.1.2, it works fine.

**Comment by wojtekn** [comment]
Also, it seems that the above crash happens when I'm using MySQL, but with incorrect credentials configured in `wp-config.php`.  When I use the correct credentials, I see a broken site:

Screenshot 2024-09-26 at 12 33 44

When I use Studio 1.1.2, both cases work: incorrect credentials show the page informing me about the problems connecting to MySQL, and correct credentials show the correct site.

**Comment by fluiddot** [comment]
> I've tested it more, but it seems that when I try to start the site configured to use MySQL, it crashes:
> 
> ```
> node:internal/errors:497
>     ErrorCaptureStackTrace(err);
>     ^
> 
> TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "set-cookie"
>     at ServerResponse.setHeader (node:_http_outgoing:655:3)
>     at /Volumes/Sites/local-environment/.webpack/main/siteServerProcess.js:61899:21
>     at Generator.next (<anonymous>)
>     at fulfilled (/Volumes/Sites/local-environment/.webpack/main/siteServerProcess.js:61839:58)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   code: 'ERR_HTTP_INVALID_HEADER_VALUE'
> }
> 
> Node.js v20.9.0
> ```
> 
> When I use Studio 1.1.2, it works fine.

@wojtekn how did you reproduce it?

Based on the error message, I wonder if it's related to https://github.com/Automattic/studio/pull/532 🤔 .

**Comment by wojtekn** [comment]
> @wojtekn how did you reproduce it?

Here are the steps:

1. Start Studio in dev mode from this branch
2. Add a site and open it in IDE
3. Remove `wp-content/database/`, `mu-plugins/sqlite-database-integration` and `wp-content/db.php`.
4. Open WP Admin

Expected behavior: the following page is served:
Screenshot 2024-09-26 at 12 40 16

Current behavior: site crashes with set-cookie error

**Comment by fluiddot** [comment]
> > @wojtekn how did you reproduce it?
> 
> Here are the steps:
> 
> 1. Start Studio in dev mode from this branch
> 2. Add a site and open it in IDE
> 3. Remove `wp-content/database/`, `mu-plugins/sqlite-database-integration` and `wp-content/db.php`.
> 4. Open WP Admin
> 
> Expected behavior: the following page is served: Screenshot 2024-09-26 at 12 40 16
> 
> Current behavior: site crashes with set-cookie error

Ah, good catch. As I shared in https://github.com/Automattic/studio/pull/561#issuecomment-2376577307, this is a bug most likely introduced in https://github.com/Automattic/studio/pull/532. I've pushed a fix in https://github.com/Automattic/studio/pull/561/commits/0f0d45eb40f067be928bb952e290023fea868516.

Now when accessing WP-Admin in the scenario shared in https://github.com/Automattic/studio/pull/561#issuecomment-2376586404, it shows the error page:

Captura de pantalla 2024-09-26 a las 12 47 47

**Review by wojtekn — APPROVED** [review]
Thanks @fluiddot , works well now.

**Comment by fluiddot** [comment]
I encountered a weird behavior when testing a site with MySQL files inside the site's folder, specifically when having the symlink `mysql.sock`. I presume this is an edge case, as users won't have these files in the site's folder, however, this uncovers a bug related to not-resolvable symlinks and the site initialization. I'll open a separate GitHub issue as it's not related to this PR.

**UPDATE:** Here's the issue 9257-gh-Automattic/dotcom-forge.

**Comment by jeroenpf** [comment]
Is this still good for a merge?

**Comment by fluiddot** [comment]
> Is this still good for a merge?

Yes, from my side it's ready to be merged :shipit: .

**Comment by fluiddot** [comment]
I noticed that the patch introduced in https://github.com/Automattic/studio/pull/532 ~~is no longer being applied~~ is giving a warning due to version mismatch but is still being applied after upgrading the Playground dependencies. I'll open a PR to update it.

**UPDATE:** Here's the PR https://github.com/Automattic/studio/pull/580.

**Pull request merged**
