### PR TITLE
Studio: Stop server that was previously started before the pull operation 

### PR DESCRIPTION
**Pull request by katinthehatsite**
## Related issues

- Fixes https://github.com/Automattic/dotcom-forge/issues/9835

## Proposed Changes

This PR ensures that the server is stopped for a started site before the pull operation starts. Previously, the server was still running for the first part of the pulling process and stopped only when the import event started. 

## Testing Instructions

* Pull the changes from this branch
* Start Studio with `STUDIO_SITE_SYNC=true npm start`
* Click on the `Sync` tab 
* Connect a WP.com site to Studio
* Start the Studio site and confirm it is running
* Start the pull operation on a site
* Observe that the server is stopped immediately and that you can not open `WP-Admin` or `Open site` links or click on a theme thumbnail to open a site

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

**Comment by ivan-ottinger** [comment]
This PR needs a rebase, but I will review it in its current state anyways and then will give it another review round after it is rebased. 🙂

**Review by ivan-ottinger — COMMENTED** [review]
The proposed changes look great and work as intended. I did not observe any regressions. 👌🏼🙂

I will give this PR a second review round once it is rebased.

The only thing (not directly related to the goal of this PR) I noticed is that the site that stopped can still be started from the sidebar:

Markup on 2024-11-19 at 16:53:05

We could display a spinner there that's already being displayed during site import. I have created a separate task for it: https://github.com/Automattic/dotcom-forge/issues/9897.

**Comment by katinthehatsite** [comment]
> We could display a spinner there that's already being displayed during site import. I have created a separate task for it

Nice thank you!

**Comment by katinthehatsite** [comment]
@ivan-ottinger I did a rebase and solved conflicts with trunk, let me know what you think!

**Review by wojtekn — APPROVED** [review]
The code change looks good, and works as expected.

Should we also prevent users from manually starting the site after we stop it? Could be follow-up issue, though.

**Comment by ivan-ottinger** [comment]
> @ivan-ottinger I did a rebase and solved conflicts with trunk, let me know what you think!

Thank you Kat, the change look great and work correctly!

---

> Should we also prevent users from manually starting the site after we stop it? Could be follow-up issue, though.

Is there any other way to start the site apart from the sidebar? 🤔 The `Start ▶️` button is already disabled during the pulling process.

**Review by ivan-ottinger — APPROVED** [review]

**Comment by wojtekn** [comment]
> Is there any other way to start the site apart from the sidebar? 🤔 The Start ▶️ button is already disabled during the pulling process.

@ivan-ottinger no, I meant sidebar. As we block the button in the site header, it would make sense to do the same in the sidebar:

Screenshot 2024-11-20 at 13 07 09

**Comment by wojtekn** [comment]
We are fixing the above under https://github.com/Automattic/dotcom-forge/issues/9897

**Pull request merged**
