### PR TITLE
Updated Windows app icon

### PR DESCRIPTION
**Pull request by matt-west**
Fixes https://github.com/Automattic/dotcom-forge/issues/6994

## Proposed Changes

- The `studio-app-icon.ico` file now contains different versions at 16, 24, 32, 48, 64, 128, and 256 pixels to avoid issues with Windows auto-scaling the icon.

## Testing Instructions

- Install Studio on Windows
- Check that the icon looks correct in the File Explorer, Settings, and Dock.

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

**Comment by matt-west** [comment]
@wojtekn I think the pixelated icon issues are due to Windows auto-scaling the icon. I’ve redrawn the icon at different sizes and combined them all into the `studio-app-icon.ico` file, but have no way to test it as I don't have a Windows machine. Can you please try this out?

I'm not sure how to update the file at `https://s0.wp.com/i/studio-app/studio-app-icon.ico?v=3` which I guess needs replacing with the new `.ico` file from this PR. Can you please take care of that.

**Comment by wojtekn** [comment]
I've added a diff: D148002-code

**Comment by wojtekn** [comment]
It didn't work, it seems it used the smallest one in all places:

Screenshot 2024-05-09 085301

It shouldn't work that way based on what [Construct your Windows app's icon](https://learn.microsoft.com/en-us/windows/apps/design/style/iconography/app-icon-construction#icon-scaling) say:

> When Windows displays your app's icon, it will look for an exact size match first. If there is no exact match it will look for the next size above and scale down.

Is it possible that Windows expects a different order of those icons? Or maybe icons were resized, but canvas size was kept the same?

**Comment by matt-west** [comment]
> Or maybe icons were resized, but canvas size was kept the same?

I think this is what happened. I resized the icons in Figma, but it was still exporting them all at 256 x 256. I’ve pushed an updated `studio-app-icon.ico` that resolves this.

**Comment by wojtekn** [comment]
Thanks @matt-west ! I updated the diff with the new icon as well. I will test it on Windows today.

**Comment by wojtekn** [comment]
Thanks @matt-west . It's much better now.

| **Before** | **After** |
|---|---|
| distorted-icon-before | distorted-icon-after |

**Review by wojtekn — APPROVED** [review]

**Comment by matt-west** [comment]
Excellent! Thanks for testing @wojtekn

**Pull request merged**
