### PR TITLE
Upgrade a8c-ci-toolkit to 3.4.2

### PR DESCRIPTION
**Pull request by wojtekn**
## Proposed Changes

I propose updating a8c Buildkite plugin to the latest version.

## Testing Instructions

1. Test if Buildkite flows still work fine.

## Pre-merge Checklist

- [x] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

**Review by AliSoftware — APPROVED** [review]
Looks all good.

But heads up that 3.4.1 doesn't yet contain the recent fix of hash_directory that just landed yesterday, so we might want to create a 3.4.2 first and migrate to that instead / next.

**Comment by wojtekn** [comment]
> But heads up that 3.4.1 doesn't yet contain the recent fix of hash_directory that just landed yesterday, so we might want to create a 3.4.2 first and migrate to that instead / next.

Yes, I'm aware of that. Thanks for making it clear, though. I opened this PR to ensure upgrade from 3.3.0 to 3.4.1 works fine while waiting for 3.4.2 to be released.

**Comment by AliSoftware** [comment]
Actually let me create a 3.4.2 version of the plugin, gimme a sec…

**Comment by wojtekn** [comment]
I compared the output for this PR build with one for the trunk:
- there is no `find: sha256sum: No such file or directory` message in output anymore
- there is no `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` hash in the cache tag and it was the hash calculated on the empty content

**Pull request merged**
