### PR TITLE
Update the label in the left sidebar when we have a single site running

### PR DESCRIPTION
**Pull request by sejas**
## Related issues

- Fixes pdtkmj-3a1-p2#comment-5982

> could we update the Stop all link label to Stop when there is only one local site?

## Proposed Changes

- update the `Stop all` link label to `Stop` when there is only one site running

## Testing Instructions

- Run `npm start`
- Start one site
- Observe it says `Stop` in the left sidebar 
- Start a second site
- Observe it says `Stop all` in the left sidebar

| Before | After |
|--------|--------|
| Screenshot 2024-12-04 at 21 20 19 | Screenshot 2024-12-04 at 21 19 32 |

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

**Comment by wojtekn** [comment]
I'm not convinced it's a good change. 🤷

**Review by katinthehatsite — APPROVED** [review]
Functionality-wise, it works as expected for me and I can see the text changing based on whether I have one site or more sites running. One advantage that I spotted while testing this in other languages is that it makes the text shorter and that button generally looks better (for example, in Ukrainian) when only one site is running. 

However, I can also see that functionality and related wording being meant for bulk managing the sites e.g. bulk stopping them. 

I feel like it is more of a design decision rather than code review call. Let's tag @matt-west for an opinion.

That said, I am approving these changes because they work as expected.

**Comment by sejas** [comment]
I like subtle details like this one. I don’t have a strong opinion on this specific change.
I can see benefits, as it follows the “plural” of the left side: `1 site running - stop` vs. `1 site running - stop all`.
Agreed that @matt-west may have a more expert opinion than I do.

**Comment by matt-west** [comment]
> I like subtle details like this one.

So do I. Thanks for changing this @sejas. The details matter! :)

**Comment by wojtekn** [comment]
Thinking forward, if we add the ability to start all sites, it would make sense to return to the original wording so we have consistent 'Start all' and 'Stop all' actions.

**Comment by sejas** [comment]
> Thinking forward, if we add the ability to start all sites, it would make sense to return to the original wording so we have consistent 'Start all' and 'Stop all' actions.

Agreed, we could change it back in the future if necessary. Maybe we don't even need to "start/stop" sites, and they are always up.

**Pull request merged**
