### PR TITLE
Improve RTL layouts

### PR DESCRIPTION
**Pull request by derekblank**
Resolves Automattic/dotcom-forge#6375

## Proposed Changes

Improves support for RTL layouts by updating compatible padding, margin, and spacing values when RTL languages are used.

## Testing Instructions

1. Change system locale to an RTL language, like Hebrew. (Steps to [change system locale on macOS](https://github.com/Automattic/dotcom-forge/issues/6375#issuecomment-2058631327), for example.)
2. Test and observe the following RTL layout-based issues are not present:

### **Change 1**: Mirror the action button icon

Before | After
-|-
צילום מסך 2024-04-19 ב-3 06 17 אח׳ | צילום מסך 2024-04-19 ב-3 05 16 אח׳

### **Change 2**: Add padding to Content tab

Before | After
-|-
צילום מסך 2024-04-19 ב-3 06 12 אח׳ | צילום מסך 2024-04-19 ב-3 05 26 אח׳

### **Change 3**: Fix label spacing and alignment on Settings tab

Before | After
-|-
צילום מסך 2024-04-19 ב-3 12 15 אח׳ |  צילום מסך 2024-05-01 ב-6 16 53 אח׳

### **Change 4**: Updates ScreenshotDemoSite background 

Before | After
-|-
צילום מסך 2024-04-19 ב-3 06 23 אח׳ |  צילום מסך 2024-04-19 ב-3 05 58 אח׳

### Known issues not addressed in this PR

* https://github.com/Automattic/dotcom-forge/issues/6662
* https://github.com/Automattic/dotcom-forge/issues/6805 (text overflow in sidebar)

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

**Comment by wojtekn** [comment]
@derekblank, as we are fixing support for RTL, should we fix the missing left black border, which seems to be the biggest difference between LTR and RTL?

צילום מסך 2024-05-02 ב-11 13 01

**Comment by matt-west** [comment]
> as we are fixing support for RTL, should we fix the missing left black border, which seems to be the biggest difference between LTR and RTL?

+1

We'd need to remove the LTR padding from the right side too. The border above the add site button should span the full-width between the content pane and the edge of the window.

Screenshot 2024-05-02 at 10 30 57

**Comment by derekblank** [comment]
>  As we are fixing support for RTL, should we fix the missing left black border, which seems to be the biggest difference between LTR and RTL?
> We'd need to remove the LTR padding from the right side too. The border above the add site button should span the full-width between the content pane and the edge of the window.

Updated for both. 👍 

צילום מסך 2024-05-02 ב-9 53 22 אח׳

**Review by wojtekn — APPROVED** [review]
Thanks @derekblank , it looks great for RTL language now.

**Pull request merged**
