### PR TITLE
Add initial support for Vietnamese

### PR DESCRIPTION
**Pull request by wojtekn**
Related to https://github.com/Automattic/dotcom-forge/issues/8189

## Proposed Changes

I propose to add support for Vietnamese.
Ảnh màn hình 2024-07-10 lúc 09 16 54

## Testing Instructions

1. Switch the OS language to Vietnamese
2. Confirm that Studio is translated

## Pre-merge Checklist

- [x] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

**Comment by htdat** [comment]
FYI. With the help of @nguyenquanghoang and reviews from A12s @htdat, @itsmeichigo, @dinhtungdu, 100% strings have been _just_ translated into Vietnamese. https://translate.wordpress.com/projects/studio/vi/default/

**Comment by nguyenquanghoang** [comment]
Amazing, Thank you so much @wojtekn @htdat

**Comment by nguyenquanghoang** [comment]
@wojtekn How can I display Vietnamese on the current Studio version (v1.0.5)?

**Comment by wojtekn** [comment]
> How can I display Vietnamese on the current Studio version (v1.0.5)?

@nguyenquanghoang the new language will be available when 1.0.6 is released. If you want to test it now, you will need to build the app locally. See https://github.com/Automattic/studio/blob/trunk/docs/code-contributions.md

**Comment by nguyenquanghoang** [comment]
Amazing, Thank you very much

**Comment by nguyenquanghoang** [comment]
@wojtekn Can I participate in the Beta and submit feedback?

**Comment by wojtekn** [comment]
@nguyenquanghoang sure, try one of those: [Mac Intel (DMG)](https://href.li/?https://cdn.a8c-ci.services/studio/studio-darwin-x64-v1.0.6-beta2.dmg), [Mac Apple Silicon (DMG)](https://href.li/?https://cdn.a8c-ci.services/studio/studio-darwin-arm64-v1.0.6-beta2.dmg), [Windows](https://href.li/?https://cdn.a8c-ci.services/studio/studio-win32-v1.0.6-beta2.exe),

**Comment by nguyenquanghoang** [comment]
@wojtekn Thank you very much 🙏

**Comment by nguyenquanghoang** [comment]
> FYI. With the help of @nguyenquanghoang and reviews from A12s @htdat, @itsmeichigo, @dinhtungdu, 100% strings have been _just_ translated into Vietnamese. https://translate.wordpress.com/projects/studio/vi/default/

@htdat can help me become a PTE for of Studio (This easily helps me proactively update and change quickly to best perfect the written translation)

**Comment by nguyenquanghoang** [comment]
@wojtekn Is there any way to fix the space between 2 paragraphs of text for languages ​​that have more characters than English? (Specifically, the characters when translated from English to Vietnamese will be longer, making the distance very difficult to see)

Fix Show Text - Studio

**Comment by wojtekn** [comment]
@nguyenquanghoang would you mind adding a separate issue for that?

**Comment by nguyenquanghoang** [comment]
@wojtekn Thank you for your clarification, I have filed a bug #372

**Comment by htdat** [comment]
> @htdat can help me become a PTE for of Studio (This easily helps me proactively update and change quickly to best perfect the written translation)

Sorry for the late response here but it sounds like you have already been a validator of the Studio project for Vietnamese https://translate.wordpress.com/profile/nguyenquanghoang/

**Comment by nguyenquanghoang** [comment]
@htdat Thanks for your support

**Pull request merged**
