### PR TITLE
Fix path to RELEASES file to let Buildkite download it

### PR DESCRIPTION
**Pull request by wojtekn**
Follow-up to https://github.com/Automattic/studio/pull/158

## Proposed Changes

Currently step that distributes files can't download RELEASES file:

```
2024-05-24 05:08:06 INFO   Searching for artifacts: "*.app.zip"
--
  | 2024-05-24 05:08:06 INFO   Found 3 artifacts. Starting to download to: /opt/ci/builds/builder/automattic/studio
  | 2024-05-24 05:08:08 INFO   Successfully downloaded "out/Studio-darwin-x64/Studio.app.zip" 173 MiB
  | 2024-05-24 05:08:08 INFO   Successfully downloaded "out/Studio-darwin-arm64/Studio.app.zip" 167 MiB
  | 2024-05-24 05:08:09 INFO   Successfully downloaded "out/Studio-darwin-universal/Studio.app.zip" 244 MiB
  | 2024-05-24 05:08:09 INFO   Searching for artifacts: "*.exe"
  | 2024-05-24 05:08:09 INFO   Found 1 artifacts. Starting to download to: /opt/ci/builds/builder/automattic/studio
  | 2024-05-24 05:08:11 INFO   Successfully downloaded "out/make/squirrel.windows/x64/studio-setup.exe" 173 MiB
  | 2024-05-24 05:08:11 INFO   Searching for artifacts: "*.nupkg"
  | 2024-05-24 05:08:11 INFO   Found 1 artifacts. Starting to download to: /opt/ci/builds/builder/automattic/studio
  | 2024-05-24 05:08:13 INFO   Successfully downloaded "out/make/squirrel.windows/x64/studio-update.nupkg" 174 MiB
  | 2024-05-24 05:08:13 INFO   Searching for artifacts: "RELEASES"
  | fatal: failed to download artifacts: No artifacts found for downloading
  | 🚨 Error: The command exited with status 1
```

I think it accepts full path or wildcard, so when it's set to file name it can't locate it. I'm trying to fix by adding a wildcard.

## Testing Instructions

Merge and check if Distribute Dev Builds goes through.

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

**Comment by emdashcodes** [comment]
@wojtekn I've tried a few similar things on Pocket Casts, and unfortunately `buildkite-agent artifact download "*" .` seems to be the only thing to correctly download `RELEASES`. 

It of course pulls down any extra artifacts you might not need, however.

**Comment by emdashcodes** [comment]
Related: https://github.com/Automattic/pocket-casts-desktop/pull/69/files#diff-a3991ebf1475eb82acab13946ffc1eca02b43917f6d5bec3898f45c8b0b9bd53

**Comment by AliSoftware** [comment]
Isn't that because the artifact is build on a Windows agent and thus uses `\` as path separators? As such, won't we need to use `*\\RELEASES` instead of `*/RELEASES` for the query of `buildkite-agent artifact download`? 🤔

**Comment by emdashcodes** [comment]
@AliSoftware The `Distribute Dev Builds` pipeline actually runs on a Mac: https://github.com/Automattic/studio/blob/94569aeee0494fe5fbb7ba357c3df913fb518a7c/.buildkite/pipeline.yml#L85

Only the actual build step uses Windows, and releases is uploaded correctly there: https://github.com/Automattic/studio/blob/94569aeee0494fe5fbb7ba357c3df913fb518a7c/.buildkite/pipeline.yml#L58-L64

**Comment by AliSoftware** [comment]
Yes but the job that contains the `studio-setup.exe`, `studio-update.nupkg` and `RELEASES` artifacts to be downloaded (i.e. the "Windows Dev Builds" and "Windows Release Builds" jobs) run on Windows agents. So in those agents and jobs we want to download the artifacts from, the paths are using `\`…
image

So from the perspective of the Mac agent doing  the `buildkite-agent artifact download`, when it will look at all the artifacts available in all the various jobs of that build to find one which has a `path` matching that query… it will see those `RELEASES` files as just having `\` strange characters in their file name (and not as directory separators). You can actually see that if you click on the `out\make\squirrel.windows\x64\RELEASES` file in the Buildkite UI to download that file to your Mac that it downloads it as `out_make_squirrel.windows_x64_RELEASES`, considering it's a single file with a giant file name with special characters, rather than file whose basename is simply `RELEASES` and which happens to be inside a set of subdirectories…

<details><summary>You can also see this if you use the REST API to ask Buildkite to list all the available artifacts of a build</summary>

```
$ curl -H "Authorization: Bearer $BUILDKITE_TOKEN" -X GET "https://api.buildkite.com/v2/organizations/automattic/pipelines/studio/builds/715/artifacts" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4991    0  4991    0     0  14740      0 --:--:-- --:--:-- --:--:-- 14766
```
```json
[
  {
    "id": "018faa93-b8c3-47de-b6ac-8870c3e3618e",
    "job_id": "018faa8f-0f9a-4b55-b7fe-055c432ce0ad",
    "url": "https://api.buildkite.com/v2/organizations/automattic/pipelines/studio/builds/715/jobs/018faa8f-0f9a-4b55-b7fe-055c432ce0ad/artifacts/018faa93-b8c3-47de-b6ac-8870c3e3618e",
    "download_url": "https://api.buildkite.com/v2/organizations/automattic/pipelines/studio/builds/715/jobs/018faa8f-0f9a-4b55-b7fe-055c432ce0ad/artifacts/018faa93-b8c3-47de-b6ac-8870c3e3618e/download",
    "state": "finished",
    "path": "out/Studio-darwin-x64/Studio.app.zip",
    "dirname": "out/Studio-darwin-x64",
    "filename": "Studio.app.zip",
    "mime_type": "application/zip",
    "file_size": 181845267,
    "glob_path": null,
    "original_path": null,
    "sha1sum": "d22ea9fe1e7534152cf10e6f991446fe16145703",
    "sha256sum": "a97e6412d0d63fd124a98135361d22e8c6eae0864b44c1069c89084211e9b99c"
  },
  {
    "id": "018faa95-bfa6-44a5-90f4-51d2848ddfaf",
    "job_id": "018faa8f-0f96-44a9-9ee6-597b5c7c72c8",
    "url": "https://api.buildkite.com/v2/organizations/automattic/pipelines/studio/builds/715/jobs/018faa8f-0f96-44a9-9ee6-597b5c7c72c8/artifacts/018faa95-bfa6-44a5-90f4-51d2848ddfaf",
    "download_url": "https://api.buildkite.com/v2/organizations/automattic/pipelines/studio/builds/715/jobs/018faa8f-0f96-44a9-9ee6-597b5c7c72c8/artifacts/018faa95-bfa6-44a5-90f4-51d2848ddfaf/download",
    "state": "finished",
    "path": "out/Studio-darwin-universal/Studio.app.zip",
    "dirname": "out/Studio-darwin-universal",
    "filename": "Studio.app.zip",
    "mime_type": "application/zip",
    "file_size": 255598566,
    "glob_path": null,
    "original_path": null,
    "sha1sum": "798b6ec708c08debe18f7be71023c445eeab0276",
    "sha256sum": "a8edec9aaf975ed7499152be76519133342ed4c4e2ab1db9bf3d5a46a8bc05ba"
  },
  {
    "id": "018faa95-e95d-4a90-b7a6-638b638302e5",
    "job_id": "018faa8f-0f9b-45d7-b312-dcdafe623347",
    "url": "https://api.buildkite.com/v2/organizations/automattic/pipelines/studio/builds/715/jobs/018faa8f-0f9b-45d7-b312-dcdafe623347/artifacts/018faa95-e95d-4a90-b7a6-638b638302e5",
    "download_url": "https://api.buildkite.com/v2/organizations/automattic/pipelines/studio/builds/715/jobs/018faa8f-0f9b-45d7-b312-dcdafe623347/artifacts/018faa95-e95d-4a90-b7a6-638b638302e5/download",
    "state": "finished",
    "path": "out/Studio-darwin-arm64/Studio.app.zip",
    "dirname": "out/Studio-darwin-arm64",
    "filename": "Studio.app.zip",
    "mime_type": "application/zip",
    "file_size": 174980759,
    "glob_path": null,
    "original_path": null,
    "sha1sum": "83710d04bb565a805ffbfd1043e32d4bd864286b",
    "sha256sum": "d823e7ce0878f6256a24b0a035806fb17b4f3d6716bc43d1c488b32515d8c229"
  },
  {
    "id": "018faa97-b35d-437a-b23b-a9157b4b207b",
    "job_id": "018faa8f-0f9e-4ce0-a8e8-ebf951325662",
    "url": "https://api.buildkite.com/v2/organizations/automattic/pipelines/studio/builds/715/jobs/018faa8f-0f9e-4ce0-a8e8-ebf951325662/artifacts/018faa97-b35d-437a-b23b-a9157b4b207b",
    "download_url": "https://api.buildkite.com/v2/organizations/automattic/pipelines/studio/builds/715/jobs/018faa8f-0f9e-4ce0-a8e8-ebf951325662/artifacts/018faa97-b35d-437a-b23b-a9157b4b207b/download",
    "state": "finished",
    "path": "out\\make\\squirrel.windows\\x64\\RELEASES",
    "dirname": ".",
    "filename": "out\\make\\squirrel.windows\\x64\\RELEASES",
    "mime_type": "",
    "file_size": 88,
    "glob_path": null,
    "original_path": null,
    "sha1sum": "8658e69194ce9f62fafeb8519ffd687a2833cb2b",
    "sha256sum": "8313ee419857e61929b3b9ac595b3b9c3841b808b089948dcbbd4dfab4802d8b"
  },
  {
    "id": "018faa97-b35e-4e58-a08a-e87be8223fd4",
    "job_id": "018faa8f-0f9e-4ce0-a8e8-ebf951325662",
    "url": "https://api.buildkite.com/v2/organizations/automattic/pipelines/studio/builds/715/jobs/018faa8f-0f9e-4ce0-a8e8-ebf951325662/artifacts/018faa97-b35e-4e58-a08a-e87be8223fd4",
    "download_url": "https://api.buildkite.com/v2/organizations/automattic/pipelines/studio/builds/715/jobs/018faa8f-0f9e-4ce0-a8e8-ebf951325662/artifacts/018faa97-b35e-4e58-a08a-e87be8223fd4/download",
    "state": "finished",
    "path": "out\\make\\squirrel.windows\\x64\\studio-setup.exe",
    "dirname": ".",
    "filename": "out\\make\\squirrel.windows\\x64\\studio-setup.exe",
    "mime_type": "application/x-ms-dos-executable",
    "file_size": 181650784,
    "glob_path": null,
    "original_path": null,
    "sha1sum": "c30cf10d6febb74d286114fd65efdbc393472fd2",
    "sha256sum": "2b57bfa190bdf6301a6a3200d987729c5fd5dab0fec41d260c502662637ee5d8"
  },
  {
    "id": "018faa97-b35f-4327-a949-c6667759bfb5",
    "job_id": "018faa8f-0f9e-4ce0-a8e8-ebf951325662",
    "url": "https://api.buildkite.com/v2/organizations/automattic/pipelines/studio/builds/715/jobs/018faa8f-0f9e-4ce0-a8e8-ebf951325662/artifacts/018faa97-b35f-4327-a949-c6667759bfb5",
    "download_url": "https://api.buildkite.com/v2/organizations/automattic/pipelines/studio/builds/715/jobs/018faa8f-0f9e-4ce0-a8e8-ebf951325662/artifacts/018faa97-b35f-4327-a949-c6667759bfb5/download",
    "state": "finished",
    "path": "out\\make\\squirrel.windows\\x64\\studio-update.nupkg",
    "dirname": ".",
    "filename": "out\\make\\squirrel.windows\\x64\\studio-update.nupkg",
    "mime_type": "",
    "file_size": 181904393,
    "glob_path": null,
    "original_path": null,
    "sha1sum": "1507c6e34faae8628eeb7707fa8c281c73464e92",
    "sha256sum": "6e9c33ff4f738f8867c0f644ffec4fb4881907e949878f4fecf0263c00140ab4"
  }
]
```
</details>

See how for the Mac entries, that REST API response looks like this, thus interpreting the `/` as directory separators:
```json
    "path": "out/Studio-darwin-x64/Studio.app.zip",
    "dirname": "out/Studio-darwin-x64",
    "filename": "Studio.app.zip",
```
But for the Windows entries it looks like this, considering the `\` as just regular characters and not directory separators:
```json
    "path": "out\\make\\squirrel.windows\\x64\\studio-update.nupkg",
    "dirname": ".",
    "filename": "out\\make\\squirrel.windows\\x64\\studio-update.nupkg",
```
And for our file of interest in particular:
```json
    "path": "out\\make\\squirrel.windows\\x64\\RELEASES",
    "dirname": ".",
    "filename": "out\\make\\squirrel.windows\\x64\\RELEASES",
```

So for all intents and purposes of the `buildkite-agent artifacts download`, the file's basename is a 38 characters filename of `out\\make\\squirrel.windows\\x64\\RELEASES` and that file resides in the `.` directory directly.

**Comment by emdashcodes** [comment]
@AliSoftware Thank you for explaining that further. You are completely right. 💯 

I pushed a test commit for Pocket Casts and `*\\RELEASES` works.

cc @wojtekn

**Pull request merged**
