### PR TITLE
Remove E2E workflow from GitHub action in favor of Buildkite

### PR DESCRIPTION
**Pull request by mokagio**
## Proposed Changes

Remove the E2E tests GitHub Actions workflow in favor of running the tests on Buildkite. This depends on #76 landing.

Internal ref paaHJt-6pg-p2

## Testing Instructions

Verify the E2E tests are green in Bulidkite and that no GitHub Action run for this PR.

## Pre-merge Checklist

- [x] Have you checked for TypeScript, React or other console errors? – N.A.

### CODE REVIEW

**Review by wojtekn — APPROVED** [review]
Looks good, thanks!

**Comment by fluiddot** [comment]
@mokagio I included this change in https://github.com/Automattic/studio/pull/76 (https://github.com/Automattic/studio/pull/76/commits/bc2f30e33b97ddfb93147e0b532f7f30e1300459) before noticing this PR. Let me now if you rather make this change here. Thanks 🙇 !

**Comment by wojtekn** [comment]
@mokagio @fluiddot I'm closing this as the other PR that makes this change was merged.

**Comment by mokagio** [comment]
@fluiddot all good. Thanks for letting me know.

**Pull request closed without merging**
