### PR TITLE
Studio: Block the text input when sending

### PR DESCRIPTION
**Pull request by kozer**
Fixes https://github.com/Automattic/dotcom-forge/issues/7932

## Proposed Changes

When the user sends a message, the input is not disabled. This PR fixes that.

## Testing Instructions

1. Naviate to assistant tabe
2. Send a message
3. Ensure that while the thinking bubble appears the input is disabled

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

**Comment by matt-west** [comment]
Can we only prevent `Enter` from submitting the input while we're waiting for a response from the assistant. Disabling the whole field feels a bit weird. It prevents the user from being able to start writing their next message and will make the [animated loading icon](https://github.com/Automattic/studio/pull/280) less visible. 

https://github.com/Automattic/studio/assets/417538/369bc0f0-a92a-423e-9ee2-10f4845bdc64

ChatGPT only disables submitting the input, but allows users to continue writing messages.

https://github.com/Automattic/studio/assets/417538/d483b756-5496-4969-89b3-0ecd3e4042cf

**Comment by fluiddot** [comment]
> Can we only prevent `Enter` from submitting the input while we're waiting for a response from the assistant. Disabling the whole field feels a bit weird. It prevents the user from being able to start writing their next message and will make the [animated loading icon](https://github.com/Automattic/studio/pull/280) less visible.

Good point. I encountered this same issue yesterday and thought of the same approach. I think the following change should do that:

```patch
diff --git forkSrcPrefix/src/components/ai-input.tsx forkDstPrefix/src/components/ai-input.tsx
index 0d6c12a1a3cfd90dcdfca5963ff31277d6494b06..6ef20530c7efbe84e330f81f9f5a38aa88776378 100644
--- forkSrcPrefix/src/components/ai-input.tsx
+++ forkDstPrefix/src/components/ai-input.tsx
@@ -62,6 +62,10 @@ export const AIInput = ( {
 	const handleKeyDownWrapper = ( e: React.KeyboardEvent< HTMLTextAreaElement > ) => {
 		if ( e.key === 'Enter' && ! e.shiftKey ) {
 			e.preventDefault();
+			if ( isAssistantThinking ) {
+				return;
+			}
+
 			if ( input.trim() !== '' ) {
 				handleSend();
 				if ( inputRef.current ) {

```

**Comment by kozer** [comment]
thank you @fluiddot , and @matt-west ! 
Updated!

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

**Comment by matt-west** [comment]
Thanks @kozer!

**Pull request merged**
