### PR TITLE
fix: Assign unique key to iterated messages

### PR DESCRIPTION
**Pull request by dcalhoun**
Relates to https://github.com/Automattic/studio/pull/315.

## Proposed Changes

Satisfy React's unique key requirement for iterating over children.

<details><summary>React key error</summary>

```
Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at http://localhost:3456/main_window/index.js:268743:48
    at div
    at div
    at div
    at ContentTabAssistant (http://localhost:3456/main_window/index.js:268758:32)
    at div
    at div
    at ContextProvider
    at ScopedContextProvider
    at ContextProvider
    at ContextProvider
    at ScopedContextProvider
    at ContextProvider
    at ContextProvider
    at ContextProvider
    at ScopedContextProvider
    at ContextProvider
    at ScopedContextProvider
    at ContextProvider
    at ContextProvider
    at ScopedContextProvider
    at Role (http://localhost:3456/main_window/index.js:276654:32)
    at div
    at UnforwardedTabPanel (http://localhost:3456/main_window/index.js:121120:3)
    at div
    at SiteContentTabs (http://localhost:3456/main_window/index.js:270224:68)
    at main
    at div
    at http://localhost:3456/main_window/index.js:1092:66
    at UnconnectedHStack (http://localhost:3456/main_window/index.js:106613:71)
    at div
    at http://localhost:3456/main_window/index.js:1092:66
    at UnconnectedVStack (http://localhost:3456/main_window/index.js:128945:71)
    at App (http://localhost:3456/main_window/index.js:268099:59)
    at ChatProvider (http://localhost:3456/main_window/index.js:271350:25)
    at PromptUsageProvider (http://localhost:3456/main_window/index.js:272361:32)
    at OnboardingProvider (http://localhost:3456/main_window/index.js:272235:31)
    at InstalledAppsProvider (http://localhost:3456/main_window/index.js:271500:34)
    at ThemeDetailsProvider (http://localhost:3456/main_window/index.js:272917:33)
    at DemoSiteUpdateProvider (http://localhost:3456/main_window/index.js:273077:35)
    at SiteDetailsProvider (http://localhost:3456/main_window/index.js:272620:32)
    at AuthProvider (http://localhost:3456/main_window/index.js:268345:25)
    at ErrorBoundary (http://localhost:3456/main_window/index.js:269737:9)
    at Root
```

</details>

## Testing Instructions

1. Chat with the Assistant.
1. Verify no errors are logged to the browser console.

## Pre-merge Checklist

- [x] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

**Comment by katinthehatsite** [comment]
There seems to be another PR fixing this issue: https://github.com/Automattic/studio/pull/325
I have approved the other one, not sure if this one would still be necessary?

**Comment by dcalhoun** [comment]
> There seems to be another PR fixing this issue: #325 I have approved the other one, not sure if this one would still be necessary?

No, they are not both necessary. The two are duplicative. I will note #325 currently results in failing unit tests, but that should be simple to resolve. 

I'll let @kozer decide if he would like to approve/merge or close this pull request. I'm happy with either approach.

**Comment by kozer** [comment]
> > There seems to be another PR fixing this issue: #325 I have approved the other one, not sure if this one would still be necessary?
> 
> 
> 
> No, they are not both necessary. The two are duplicative. I will note #325 currently results in failing unit tests, but that should be simple to resolve. 
> 
> 
> 
> I'll let @kozer decide if he would like to approve/merge or close this pull request. I'm happy with either approach. 

Do you mind if we close this one and merge the other, that fixes the message id, and use that as key?
I can remove the div and add Fragment same as this one. However, it's EOD for me today, so feel free to make that change, or if it's ok let's wait till Monday. 

Is it ok?
@dcalhoun

**Comment by dcalhoun** [comment]
> Do you mind if we close this one and merge the other, that fixes the message id, and use that as key? I can remove the div and add Fragment same as this one. However, it's EOD for me today, so feel free to make that change, or if it's ok let's wait till Monday.
> 
> Is it ok?

I don't mind at all. Thanks! 🚀 

Closing in favor of #324.

**Pull request closed without merging**
