### PR TITLE
Change link to new-hosted-site flow for new sync sites

### PR DESCRIPTION
**Pull request by sejas**
## Related issues

- Related to https://github.com/Automattic/dotcom-forge/issues/9359

## Proposed Changes

- Open `new-hosted-site` which creates a new site and moves it to atomic by default
- Pass the current siteId as a param so we can save it in the flow
- Add ref "studio" to track it

## Testing Instructions

There will be an wpcalypso PR that you can use for testing.
The following steps will work on production even without that PR.

- Run `STUDIO_SITE_SYNC=true npm start`
- Click on the Sync tab
- Click on "Create new site ↗"
- Observe the plan selector opens with only the business and ecommerce plans
- Observe the URL contains the param `studio-site-id`
- Continue the flow and purchase a site
- Observe you've created a new site that is atomic

Screenshot 2024-11-22 at 19 38 49

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

### CODE REVIEW

**Comment by wojtekn** [comment]
@sejas it works as expected. Should we just skip the `showDomainStep` param to show plans immediately? That step seems a bit outdated.

**Review by wojtekn — APPROVED** [review]

**Comment by sejas** [comment]
> it works as expected. Should we just skip the showDomainStep param to show plans immediately? That step seems a bit outdated.

I've removed the `showDomainStep`, it's an easy change that we can set it back if needed.

**Review by ivan-ottinger — COMMENTED** [review]
The changes look great. 👌🏼🙂 

However, after the last commit (removing the domain selection step), it doesn't seem to be possible to get through the plan selection screen:

Markup on 2024-11-25 at 10:40:30

It is due to the following error:

```
ProcessingStep failed: BlogNameExistsError: Sorry, that site already exists!
```

**Comment by sejas** [comment]
> The changes look great. 👌🏼🙂
> 
> However, after the last commit (removing the domain selection step), it doesn't seem to be possible to get through the plan selection screen:
> 
> Markup on 2024-11-25 at 10:40:30
> 
> It is due to the following error:
> 
> ```
> ProcessingStep failed: BlogNameExistsError: Sorry, that site already exists!
> ```

Can you try starting the flow from [wp.com/hosting](https://wp.com/hosting) -> Create Site ?
I saw that error when developing, but eventually the error was gone and I couldn't reproduce it. I agree that using a domain selector is a safer approach until that error is fixed.

**Comment by ivan-ottinger** [comment]
> Can you try starting the flow from [wp.com/hosting](https://wp.com/hosting) -> Create Site ?

I was able to reproduce it there as well.

> I saw that error when developing, but eventually the error was gone and I couldn't reproduce it. I agree that using a domain selector is a safer approach until that error is fixed.

Looks like it happens when one starts the flow, but then leaves it before finishing _without_ emptying the cart.

Since this is not related to your PR, I am approving it.

Also going to check if that issue has been reported already.

**Review by ivan-ottinger — APPROVED** [review]

**Comment by ivan-ottinger** [comment]
> Looks like it happens when one starts the flow, but then leaves it before finishing without emptying the cart.

Interesting. I cannot reproduce the same issue anymore. It doesn't seem to be caused by not emptying the cart either. It is not clear how it got triggered for me before.

I will try a couple more times and if I can reproduce it, I will create a bug report and investigate it further.

**Pull request merged**
